artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/315351007376350403/3b8d21fa0cfc4da085e9fc90b9a8dd19/artifacts
end_time: 1675858840563
entry_point_name: ''
experiment_id: '315351007376350403'
lifecycle_stage: active
run_id: 3b8d21fa0cfc4da085e9fc90b9a8dd19
run_name: intrigued-flea-541
run_uuid: 3b8d21fa0cfc4da085e9fc90b9a8dd19
source_name: ''
source_type: 4
source_version: ''
start_time: 1675858750119
status: 4
tags: []
user_id: p403830
