artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/623527813472324037/779db465e5d74df28386dfa530bb0b71/artifacts
end_time: null
entry_point_name: ''
experiment_id: '623527813472324037'
lifecycle_stage: active
run_id: 779db465e5d74df28386dfa530bb0b71
run_name: ambitious-moose-684
run_uuid: 779db465e5d74df28386dfa530bb0b71
source_name: ''
source_type: 4
source_version: ''
start_time: 1675846860701
status: 1
tags: []
user_id: p403830
