artifact_location: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/mlrun_save/221166958779942422
creation_time: 1685475362221
experiment_id: '221166958779942422'
last_update_time: 1685475362221
lifecycle_stage: active
name: benchmark_LCG_right_inv_temp_3SAT
