artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/experiment_tracking/experiments_storing/275879951322576639/26cb80de0e5844ca9ca0d2b730fa1606/artifacts
end_time: 1673430568206
entry_point_name: ''
experiment_id: '275879951322576639'
lifecycle_stage: active
run_id: 26cb80de0e5844ca9ca0d2b730fa1606
run_name: handsome-finch-477
run_uuid: 26cb80de0e5844ca9ca0d2b730fa1606
source_name: ''
source_type: 4
source_version: ''
start_time: 1673430460399
status: 3
tags: []
user_id: p403830
