artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/126765780492281712/3de5ae83e9a2428c8d306b3231dfb415/artifacts
end_time: null
entry_point_name: ''
experiment_id: '126765780492281712'
lifecycle_stage: active
run_id: 3de5ae83e9a2428c8d306b3231dfb415
run_name: agreeable-sponge-451
run_uuid: 3de5ae83e9a2428c8d306b3231dfb415
source_name: ''
source_type: 4
source_version: ''
start_time: 1675756869648
status: 1
tags: []
user_id: p403830
