artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/872138274865442125/da49d842155a4481a05dfcd74a9d4eb6/artifacts
end_time: null
entry_point_name: ''
experiment_id: '872138274865442125'
lifecycle_stage: active
run_id: da49d842155a4481a05dfcd74a9d4eb6
run_name: luxuriant-fly-897
run_uuid: da49d842155a4481a05dfcd74a9d4eb6
source_name: ''
source_type: 4
source_version: ''
start_time: 1675842581249
status: 1
tags: []
user_id: p403830
