artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/872138274865442125/f6286ed10a9a4f9ea87eac6f0ce7ec2c/artifacts
end_time: 1675793738634
entry_point_name: ''
experiment_id: '872138274865442125'
lifecycle_stage: active
run_id: f6286ed10a9a4f9ea87eac6f0ce7ec2c
run_name: sincere-lark-471
run_uuid: f6286ed10a9a4f9ea87eac6f0ce7ec2c
source_name: ''
source_type: 4
source_version: ''
start_time: 1675793734733
status: 4
tags: []
user_id: p403830
