artifact_location: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/495583015339755049
creation_time: 1675250016174
experiment_id: '495583015339755049'
last_update_time: 1675250016174
lifecycle_stage: active
name: mlflow-random_3SAT-medium
