image: python:3.10.8

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install safety
  - pip install -r requirements.txt

stages:
    - safety

safety:
  stage: safety
  script:
    - safety check || exit 1