fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--diff, --check]

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.902
#    hooks:
#      - id: mypy
#        exclude: ^tests/
#        args: [--ignore-missing-imports, --allow-redefinition]

#  - repo: https://github.com/pre-commit/mirrors-pylint
#    rev: v3.0.0a3
#    hooks:
#      - id: pylint
#        args: [--enable=unused-import]
#