fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--diff, --check]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        #files: ^python/src/
        exclude: ^tests/
        args: [--ignore-missing-imports, --allow-redefinition]

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
        - id: pydocstyle
          args:
          - --ignore=D104,D203,D212,D213,D214,D215,D404,D405,D406,D407,D408,D409,D410,D411,D413,D415,D416,D417
          exclude: ^tests/

#  - repo: https://github.com/pre-commit/mirrors-pylint
#    rev: v3.0.0a3
#    hooks:
#      - id: pylint
#        args: [--enable=unused-import, max-line-length=140]
