artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/623527813472324037/f70df0ce795b49deb39405d53a55dd64/artifacts
end_time: null
entry_point_name: ''
experiment_id: '623527813472324037'
lifecycle_stage: active
run_id: f70df0ce795b49deb39405d53a55dd64
run_name: masked-bee-749
run_uuid: f70df0ce795b49deb39405d53a55dd64
source_name: ''
source_type: 4
source_version: ''
start_time: 1675767431740
status: 1
tags: []
user_id: p403830
