artifact_location: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/126765780492281712
creation_time: 1675756869508
experiment_id: '126765780492281712'
last_update_time: 1675756869508
lifecycle_stage: active
name: mlflow-random_3SAT-medium-GCN
