artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/experiment_tracking/experiments_storing/694196827076527850/ca6839de35da4da396b922e4048fda4b/artifacts
end_time: 1675172595396
entry_point_name: ''
experiment_id: '694196827076527850'
lifecycle_stage: active
run_id: ca6839de35da4da396b922e4048fda4b
run_name: rebellious-fowl-459
run_uuid: ca6839de35da4da396b922e4048fda4b
source_name: ''
source_type: 4
source_version: ''
start_time: 1675172583540
status: 4
tags: []
user_id: p403830
