artifact_location: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/experiment_tracking/experiments_storing/694196827076527850
creation_time: 1673942933425
experiment_id: '694196827076527850'
last_update_time: 1673942933425
lifecycle_stage: active
name: mlflow-demo2
