artifact_location: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/mlrun_save/330774539182474496
creation_time: 1684936066841
experiment_id: '330774539182474496'
last_update_time: 1684936066841
lifecycle_stage: active
name: blocksworld_vcg_interaction
