artifact_location: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/715978646431075251
creation_time: 1675252485770
experiment_id: '715978646431075251'
last_update_time: 1675252485770
lifecycle_stage: active
name: mlflow-blocksat_interactionNN
