artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/experiment_tracking/experiments_storing/694196827076527850/70282c55322c406f9bd7218fee6c6e30/artifacts
end_time: null
entry_point_name: ''
experiment_id: '694196827076527850'
lifecycle_stage: active
run_id: 70282c55322c406f9bd7218fee6c6e30
run_name: sincere-shad-741
run_uuid: 70282c55322c406f9bd7218fee6c6e30
source_name: ''
source_type: 4
source_version: ''
start_time: 1675175187525
status: 1
tags: []
user_id: p403830
