artifact_location: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/315351007376350403
creation_time: 1675847620341
experiment_id: '315351007376350403'
last_update_time: 1675847620341
lifecycle_stage: active
name: mlflow-blocksat_interaction_LCG
