artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/315351007376350403/e374a090dede4b5bb38ec92ee0b65262/artifacts
end_time: null
entry_point_name: ''
experiment_id: '315351007376350403'
lifecycle_stage: active
run_id: e374a090dede4b5bb38ec92ee0b65262
run_name: gentle-lynx-28
run_uuid: e374a090dede4b5bb38ec92ee0b65262
source_name: ''
source_type: 4
source_version: ''
start_time: 1676989009916
status: 1
tags: []
user_id: p403830
