artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/872138274865442125/13e52e599bdd4d4c8be1da23bac68d67/artifacts
end_time: null
entry_point_name: ''
experiment_id: '872138274865442125'
lifecycle_stage: active
run_id: 13e52e599bdd4d4c8be1da23bac68d67
run_name: mysterious-croc-165
run_uuid: 13e52e599bdd4d4c8be1da23bac68d67
source_name: ''
source_type: 4
source_version: ''
start_time: 1675844416231
status: 1
tags: []
user_id: p403830
