artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/315351007376350403/f1f9e26fea314a949c5d0f9fe1581a9f/artifacts
end_time: null
entry_point_name: ''
experiment_id: '315351007376350403'
lifecycle_stage: active
run_id: f1f9e26fea314a949c5d0f9fe1581a9f
run_name: invincible-sheep-205
run_uuid: f1f9e26fea314a949c5d0f9fe1581a9f
source_name: ''
source_type: 4
source_version: ''
start_time: 1675850753074
status: 1
tags: []
user_id: p403830
