artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/315351007376350403/f930ac0b52a1403f9a295fce9d4627d5/artifacts
end_time: null
entry_point_name: ''
experiment_id: '315351007376350403'
lifecycle_stage: active
run_id: f930ac0b52a1403f9a295fce9d4627d5
run_name: unleashed-grub-13
run_uuid: f930ac0b52a1403f9a295fce9d4627d5
source_name: ''
source_type: 4
source_version: ''
start_time: 1675847620485
status: 1
tags: []
user_id: p403830
