artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/315351007376350403/eaab033d41e746aebd280a0e754ff633/artifacts
end_time: null
entry_point_name: ''
experiment_id: '315351007376350403'
lifecycle_stage: active
run_id: eaab033d41e746aebd280a0e754ff633
run_name: wise-quail-585
run_uuid: eaab033d41e746aebd280a0e754ff633
source_name: ''
source_type: 4
source_version: ''
start_time: 1675850975468
status: 1
tags: []
user_id: p403830
