artifact_location: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/mlrun_save/453056482082015836
creation_time: 1684935615616
experiment_id: '453056482082015836'
last_update_time: 1684935615616
lifecycle_stage: active
name: random_3SAT
