artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/315351007376350403/cfecec049a9147cebfff4f7d214a89af/artifacts
end_time: null
entry_point_name: ''
experiment_id: '315351007376350403'
lifecycle_stage: active
run_id: cfecec049a9147cebfff4f7d214a89af
run_name: serious-mouse-260
run_uuid: cfecec049a9147cebfff4f7d214a89af
source_name: ''
source_type: 4
source_version: ''
start_time: 1675859553450
status: 1
tags: []
user_id: p403830
