artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/mlrun_save/221166958779942422/a1746c4cc3374d8d8cc2ba948e3365d4/artifacts
end_time: null
entry_point_name: ''
experiment_id: '221166958779942422'
lifecycle_stage: active
run_id: a1746c4cc3374d8d8cc2ba948e3365d4
run_name: bittersweet-foal-994
run_uuid: a1746c4cc3374d8d8cc2ba948e3365d4
source_name: ''
source_type: 4
source_version: ''
start_time: 1685525974215
status: 1
tags: []
user_id: p403830
