artifact_location: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/418199050093741489
creation_time: 1675249537303
experiment_id: '418199050093741489'
last_update_time: 1675249537303
lifecycle_stage: active
name: mlflow-random_3SAT-small
