artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/experiment_tracking/experiments_storing/694196827076527850/f4f4b35bc9bf43dc9c2ad128e37b77d1/artifacts
end_time: 1675170447780
entry_point_name: ''
experiment_id: '694196827076527850'
lifecycle_stage: active
run_id: f4f4b35bc9bf43dc9c2ad128e37b77d1
run_name: unleashed-crab-299
run_uuid: f4f4b35bc9bf43dc9c2ad128e37b77d1
source_name: ''
source_type: 4
source_version: ''
start_time: 1675170350405
status: 4
tags: []
user_id: p403830
