artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/experiment_tracking/experiments_storing/694196827076527850/35b9882298dc4d75a193fde78f5e0d2e/artifacts
end_time: null
entry_point_name: ''
experiment_id: '694196827076527850'
lifecycle_stage: active
run_id: 35b9882298dc4d75a193fde78f5e0d2e
run_name: illustrious-bird-493
run_uuid: 35b9882298dc4d75a193fde78f5e0d2e
source_name: ''
source_type: 4
source_version: ''
start_time: 1675171866307
status: 1
tags: []
user_id: p403830
