artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/547839900408846355/93f84ad1cef947acbe907a571c2dfab5/artifacts
end_time: null
entry_point_name: ''
experiment_id: '547839900408846355'
lifecycle_stage: active
run_id: 93f84ad1cef947acbe907a571c2dfab5
run_name: ambitious-jay-398
run_uuid: 93f84ad1cef947acbe907a571c2dfab5
source_name: ''
source_type: 4
source_version: ''
start_time: 1675253621820
status: 1
tags: []
user_id: p403830
