artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/mlrun_save/221166958779942422/81af1e4ecfee474ea2f38f422aea56b0/artifacts
end_time: 1685475362834
entry_point_name: ''
experiment_id: '221166958779942422'
lifecycle_stage: active
run_id: 81af1e4ecfee474ea2f38f422aea56b0
run_name: loud-sponge-160
run_uuid: 81af1e4ecfee474ea2f38f422aea56b0
source_name: ''
source_type: 4
source_version: ''
start_time: 1685475362382
status: 4
tags: []
user_id: p403830
