artifact_location: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/454811474437127363
creation_time: 1675765847559
experiment_id: '454811474437127363'
last_update_time: 1675765847559
lifecycle_stage: active
name: mlflow-random_3SAT-medium-GCN-LCG
