artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/experiment_tracking/experiments_storing/275879951322576639/dfd7018134fe41d29d49d00ef3273bae/artifacts
end_time: 1673439189465
entry_point_name: ''
experiment_id: '275879951322576639'
lifecycle_stage: active
run_id: dfd7018134fe41d29d49d00ef3273bae
run_name: capricious-hawk-529
run_uuid: dfd7018134fe41d29d49d00ef3273bae
source_name: ''
source_type: 4
source_version: ''
start_time: 1673438939078
status: 3
tags: []
user_id: p403830
