artifact_location: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/experiment_tracking/experiments_storing/275879951322576639
creation_time: 1673430460271
experiment_id: '275879951322576639'
last_update_time: 1673430460271
lifecycle_stage: active
name: mlflow-demo2
