artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/experiment_tracking/experiments_storing/275879951322576639/c6ad19ab93cb43fda1a842a8f3aaace2/artifacts
end_time: 1673431003177
entry_point_name: ''
experiment_id: '275879951322576639'
lifecycle_stage: active
run_id: c6ad19ab93cb43fda1a842a8f3aaace2
run_name: magnificent-eel-338
run_uuid: c6ad19ab93cb43fda1a842a8f3aaace2
source_name: ''
source_type: 4
source_version: ''
start_time: 1673430904942
status: 3
tags: []
user_id: p403830
