artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/mlrun_save/907692526338907233/9ce03499d54d40c8a6a4f836efa159ad/artifacts
end_time: null
entry_point_name: ''
experiment_id: '907692526338907233'
lifecycle_stage: active
run_id: 9ce03499d54d40c8a6a4f836efa159ad
run_name: hilarious-cub-76
run_uuid: 9ce03499d54d40c8a6a4f836efa159ad
source_name: ''
source_type: 4
source_version: ''
start_time: 1689189058693
status: 1
tags: []
user_id: p403830
