artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/872138274865442125/fdde1cef6ecb4284bf64750ab3620056/artifacts
end_time: null
entry_point_name: ''
experiment_id: '872138274865442125'
lifecycle_stage: active
run_id: fdde1cef6ecb4284bf64750ab3620056
run_name: delightful-chimp-19
run_uuid: fdde1cef6ecb4284bf64750ab3620056
source_name: ''
source_type: 4
source_version: ''
start_time: 1675846425251
status: 1
tags: []
user_id: p403830
