artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/315351007376350403/a5f80a1ca35241a5baffb94e3fdd2023/artifacts
end_time: null
entry_point_name: ''
experiment_id: '315351007376350403'
lifecycle_stage: active
run_id: a5f80a1ca35241a5baffb94e3fdd2023
run_name: marvelous-gnat-68
run_uuid: a5f80a1ca35241a5baffb94e3fdd2023
source_name: ''
source_type: 4
source_version: ''
start_time: 1675851315333
status: 1
tags: []
user_id: p403830
