artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/900011981694909930/f4a99fca0aa243c487cedc379d1f3d3b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '900011981694909930'
lifecycle_stage: active
run_id: f4a99fca0aa243c487cedc379d1f3d3b
run_name: bold-hen-139
run_uuid: f4a99fca0aa243c487cedc379d1f3d3b
source_name: ''
source_type: 4
source_version: ''
start_time: 1675754765403
status: 1
tags: []
user_id: p403830
