artifact_location: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/623527813472324037
creation_time: 1675766006886
experiment_id: '623527813472324037'
last_update_time: 1675766006886
lifecycle_stage: active
name: mlflow-blocksat_GCN_LCG
