artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/experiment_tracking/experiments_storing/275879951322576639/df3b85d8acde446589eaf67ef07e56f7/artifacts
end_time: 1673436494034
entry_point_name: ''
experiment_id: '275879951322576639'
lifecycle_stage: active
run_id: df3b85d8acde446589eaf67ef07e56f7
run_name: dapper-cub-768
run_uuid: df3b85d8acde446589eaf67ef07e56f7
source_name: ''
source_type: 4
source_version: ''
start_time: 1673436201182
status: 3
tags: []
user_id: p403830
