artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/315351007376350403/a48d1f9fe20f4854b4dd1bf6608b38c9/artifacts
end_time: null
entry_point_name: ''
experiment_id: '315351007376350403'
lifecycle_stage: active
run_id: a48d1f9fe20f4854b4dd1bf6608b38c9
run_name: treasured-sloth-73
run_uuid: a48d1f9fe20f4854b4dd1bf6608b38c9
source_name: ''
source_type: 4
source_version: ''
start_time: 1675858073112
status: 1
tags: []
user_id: p403830
