artifact_location: file:///home/ubuntu/GIT_ML/ml_based_sat_solver/mlrun_save/679335541187574041
creation_time: 1684926246794
experiment_id: '679335541187574041'
last_update_time: 1684926246794
lifecycle_stage: active
name: blocksworld_vcg_interaction
