artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/experiment_tracking/experiments_storing/275879951322576639/01edca97e1de404ebe048f007adbebe6/artifacts
end_time: 1673432122652
entry_point_name: ''
experiment_id: '275879951322576639'
lifecycle_stage: active
run_id: 01edca97e1de404ebe048f007adbebe6
run_name: placid-gnu-967
run_uuid: 01edca97e1de404ebe048f007adbebe6
source_name: ''
source_type: 4
source_version: ''
start_time: 1673432021804
status: 3
tags: []
user_id: p403830
