artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/experiment_tracking/experiments_storing/694196827076527850/0ddd42f964b14b46af735ca3ac83d7dc/artifacts
deleted_time: 1673943751504
end_time: 1673943241212
entry_point_name: ''
experiment_id: '694196827076527850'
lifecycle_stage: deleted
run_id: 0ddd42f964b14b46af735ca3ac83d7dc
run_name: resilient-roo-14
run_uuid: 0ddd42f964b14b46af735ca3ac83d7dc
source_name: ''
source_type: 4
source_version: ''
start_time: 1673943156441
status: 4
tags: []
user_id: p403830
