artifact_location: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/674915516478619079
creation_time: 1675838675608
experiment_id: '674915516478619079'
last_update_time: 1675838675608
lifecycle_stage: active
name: mlflow-blocksat_Interaction_LCG
