artifact_location: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML3/ml_based_sat_solver/mlrun_save/907692526338907233
creation_time: 1689189058516
experiment_id: '907692526338907233'
last_update_time: 1689189058516
lifecycle_stage: active
name: one_sample
