artifact_location: file:///home/ubuntu/GIT_ML_MAIN/ml_based_sat_solver/mlrun_save/603983687658095993
creation_time: 1684934129504
experiment_id: '603983687658095993'
last_update_time: 1684934129504
lifecycle_stage: active
name: benchmark_LCG_VCG_broadcast_test
