artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/872138274865442125/5baf70a0d2cb4ee49d6f442c9d927d32/artifacts
end_time: null
entry_point_name: ''
experiment_id: '872138274865442125'
lifecycle_stage: active
run_id: 5baf70a0d2cb4ee49d6f442c9d927d32
run_name: tasteful-shrew-238
run_uuid: 5baf70a0d2cb4ee49d6f442c9d927d32
source_name: ''
source_type: 4
source_version: ''
start_time: 1675842751352
status: 1
tags: []
user_id: p403830
