name: Security Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_check:
    name: Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Python commands
        run: |
          pip install --upgrade pip
          python3.10 -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          safety check
