artifact_location: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/872138274865442125
creation_time: 1675793626266
experiment_id: '872138274865442125'
last_update_time: 1675793626266
lifecycle_stage: active
name: mlflow-random_3SAT-medium-Interaction-LCG_subset
