artifact_uri: file:///Users/p403830/Library/CloudStorage/OneDrive-PorscheDigitalGmbH/GIT_SAT_ML/ml_based_sat_solver/mlrun/315351007376350403/1db7b3fb8ef74026ae937193ca75769e/artifacts
end_time: null
entry_point_name: ''
experiment_id: '315351007376350403'
lifecycle_stage: active
run_id: 1db7b3fb8ef74026ae937193ca75769e
run_name: beautiful-worm-20
run_uuid: 1db7b3fb8ef74026ae937193ca75769e
source_name: ''
source_type: 4
source_version: ''
start_time: 1676990679289
status: 1
tags: []
user_id: p403830
